version: 2
registries:
  hex-organization-oban:
    type: hex-organization
    organization: oban
    key: "${{secrets.HEX_ORGANIZATION_OBAN_KEY}}"

updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: main
  ignore:
  - dependency-name: ecto
    versions:
    - 3.6.1
  - dependency-name: eventstore
    versions:
    - 1.2.1
    - 1.2.2
  - dependency-name: excoveralls
    versions:
    - 0.13.4
  registries:
  - hex-organization-oban
